---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-gpu-sharing-run-ai-v1alpha1-gpusharingconfig
  failurePolicy: Fail
  name: vgpusharingconfig-v1alpha1.kb.io
  rules:
  - apiGroups:
    - gpu-sharing.run.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gpusharingconfigs
  sideEffects: None
