---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gpu-sharing.run.ai
  resources:
  - gpusharingconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gpu-sharing.run.ai
  resources:
  - gpusharingconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - gpu-sharing.run.ai
  resources:
  - gpusharingconfigs/status
  verbs:
  - get
  - patch
  - update
