//go:build !ignore_autogenerated

// Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FractioningAgentSpec) DeepCopyInto(out *FractioningAgentSpec) {
	*out = *in
	if in.FailOpen != nil {
		in, out := &in.FailOpen, &out.FailOpen
		*out = new(bool)
		**out = **in
	}
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.StableThreshold != nil {
		in, out := &in.StableThreshold, &out.StableThreshold
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.ReadinessPort != nil {
		in, out := &in.ReadinessPort, &out.ReadinessPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FractioningAgentSpec.
func (in *FractioningAgentSpec) DeepCopy() *FractioningAgentSpec {
	if in == nil {
		return nil
	}
	out := new(FractioningAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuFractioningConfig) DeepCopyInto(out *GpuFractioningConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuFractioningConfig.
func (in *GpuFractioningConfig) DeepCopy() *GpuFractioningConfig {
	if in == nil {
		return nil
	}
	out := new(GpuFractioningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuFractioningConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuFractioningConfigList) DeepCopyInto(out *GpuFractioningConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GpuFractioningConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuFractioningConfigList.
func (in *GpuFractioningConfigList) DeepCopy() *GpuFractioningConfigList {
	if in == nil {
		return nil
	}
	out := new(GpuFractioningConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GpuFractioningConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuFractioningConfigSpec) DeepCopyInto(out *GpuFractioningConfigSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FractioningAgent != nil {
		in, out := &in.FractioningAgent, &out.FractioningAgent
		*out = new(FractioningAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricsAgent != nil {
		in, out := &in.MetricsAgent, &out.MetricsAgent
		*out = new(MetricsAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MpsDaemon != nil {
		in, out := &in.MpsDaemon, &out.MpsDaemon
		*out = new(MpsDaemonSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuFractioningConfigSpec.
func (in *GpuFractioningConfigSpec) DeepCopy() *GpuFractioningConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GpuFractioningConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GpuFractioningConfigStatus) DeepCopyInto(out *GpuFractioningConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GpuFractioningConfigStatus.
func (in *GpuFractioningConfigStatus) DeepCopy() *GpuFractioningConfigStatus {
	if in == nil {
		return nil
	}
	out := new(GpuFractioningConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricNamesSpec) DeepCopyInto(out *MetricNamesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricNamesSpec.
func (in *MetricNamesSpec) DeepCopy() *MetricNamesSpec {
	if in == nil {
		return nil
	}
	out := new(MetricNamesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsAgentSpec) DeepCopyInto(out *MetricsAgentSpec) {
	*out = *in
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricNames != nil {
		in, out := &in.MetricNames, &out.MetricNames
		*out = new(MetricNamesSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsAgentSpec.
func (in *MetricsAgentSpec) DeepCopy() *MetricsAgentSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MpsDaemonSpec) DeepCopyInto(out *MpsDaemonSpec) {
	*out = *in
	if in.RuntimeClassName != nil {
		in, out := &in.RuntimeClassName, &out.RuntimeClassName
		*out = new(string)
		**out = **in
	}
	if in.Backoff != nil {
		in, out := &in.Backoff, &out.Backoff
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int32)
		**out = **in
	}
	if in.StableThreshold != nil {
		in, out := &in.StableThreshold, &out.StableThreshold
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GracefulStopDelay != nil {
		in, out := &in.GracefulStopDelay, &out.GracefulStopDelay
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MpsDaemonSpec.
func (in *MpsDaemonSpec) DeepCopy() *MpsDaemonSpec {
	if in == nil {
		return nil
	}
	out := new(MpsDaemonSpec)
	in.DeepCopyInto(out)
	return out
}
