replicaCount: 1
leaderElect: true

images:
  operator:
    repository: gcr.io/run-ai-prod/gpu-sharing-operator
    tag: ""
    pullPolicy: IfNotPresent
  sharingd:
    repository: gcr.io/run-ai-prod/sharingd
    tag: ""
    pullPolicy: IfNotPresent
  metricsd:
    repository: gcr.io/run-ai-prod/metricsd
    tag: ""
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  operator:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
