apiVersion: gpu-sharing.run.ai/v1alpha1
kind: GpuSharingConfig
metadata:
  name: default
  labels:
    {{- include "gpu-sharing-operator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  nodeSelector:
    nvidia.com/gpu.present: "true"
  metricsAgent:
    enabled: {{ .Values.metricsAgent.enabled }}
  {{- with .Values.metricsAgent }}
  {{- if or .extraEnv .extraVolumeMounts .extraVolumes }}
    {{- with .extraEnv }}
    extraEnv:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .extraVolumeMounts }}
    extraVolumeMounts:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .extraVolumes }}
    extraVolumes:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
