{{/*
Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-fractioning.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-fractioning.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "gpu-fractioning.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
