# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: gpu-fractioning.kai.scheduler/v1alpha1
kind: GpuFractioningConfig
metadata:
  name: default
spec: {}
